name: Test Design Patterns

on:
  push:
    branches:
      - main # Customize this to your desired branch trigger

jobs:
  test_modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # or 'temurin', 'zulu', etc.
          java-version: '17' # replace with your required Java version

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.gradle/caches
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}"
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install dependencies
        run: cd ./Builder && ./gradlew clean build

      # Test each module
      - name: Test Factory Module
        run: cd ./Factory && ./gradlew test --stacktrace
        continue-on-error: true

      - name: Test Prototype Module
        run: cd ./Prototype && ./gradlew test --stacktrace
        continue-on-error: true

      - name: Test Singleton Module
        run: cd ./Singleton && ./gradlew test --stacktrace
        continue-on-error: true

      # You can add more test steps for other modules
      - name: Upload test results as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test_results
          path: |
            **/build/test-results/**/*.xml